# Generated by Django 4.2.5 on 2023-10-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('duration_in_sec', models.PositiveIntegerField()),
                ('link', models.URLField(blank=True)),
                ('check_correct', models.BooleanField(default=False)),
                ('time_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
