# Generated by Django 4.2.5 on 2023-10-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='lessons',
            name='duration_in_sec',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lessons',
            name='product',
            field=models.ManyToManyField(to='system.product'),
        ),
    ]
