# Generated by Django 4.2.5 on 2023-10-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_productaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaccess',
            name='lesson',
        ),
        migrations.AddField(
            model_name='productaccess',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.product'),
        ),
    ]
