# Generated by Django 4.2.5 on 2023-10-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_lessons_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='check_correct',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='lesson',
            field=models.ManyToManyField(blank=True, to='system.lessons'),
        ),
    ]
